export const DefaultPhysicalAttachmentTemplate =
  "Date: {{booking_date}}<br><br>{{membership_address}}<br><br><br>Dear Sir/Madam,<br><br>AUTHORISATION LETTER - {{attraction_name}}<br><br>Singapore Sports School hereby authorise our employee identified below, to utilise our {{corp_pass_number}} pass(s) on the date as indicated.<br><br><br>Date of Visit: {{visit_date}}<br><br>Name of Employee: {{borrower_name}}<br><br><br>Thank you.<br><br><br>Human Resource Department<br>(This is a system generated letter.)";

export const DefaultElectronicAttachmentTemplate =
  "Date: {{ballot_date}}<br><br>CORPORATE LETTER<br>{{attraction_name}}<br><br><br><br><br><br><br>This is to certify that the following employee is authorised to visit Singapore Zoo & River Wonders under your Company's Corporate Membership number {{corp_pass_number}}<br><br>Employee: {{borrower_name}}<br><br>Date of Visit: {{visit_date}}<br><br>Present this letter to enjoy up to 20% discount at selected Retail and F&B outlets.<br><br>Terms and Conditions<br><br><ul><li>All corporate members must secure a time slot via https://managebooking.mandai.com/ and comply to MWR Safe Management Measures for your safety and well-being, otherwise entry is not allowed.Time slot bookings are subject to availability, on a first come, first served basis.</li><li>Each letter allows complimentary admission to Singapore Zoo & River Wonders for up to four (4) persons, one of whom must be an employee of the corporate member named above. The employee must be present and produce valid staff pass or NRIC along with the signed letter for benefit to apply.</li><li>Each letter can only be used ONCE a day.</li><li>In the event of unauthorized use or copy of the letter, Singapore Zoo & River Wonders will deny entry and verification will be done with the company which will take appropriate action for any wilful violation.</li><li>In the event that the letter is detected to be presented more than once on the same day; the employee will be liable for the additional entry at Singapore Zoo & River Wonders prevailing walk-in rate accordingly.</li><li>Your existing Corporate Membership will expire once the validity period is over.</li></li></ul>In addition, you shall adhere to the Membership terms and conditions stated https://www.mandai.com/en/memberships/corporate-membership.html during your visit.<br><br>Best Regards,<br><br><br>Manager, Human Resource";

export const ElectronicAttachmentVariables =
  "{{ballot_date}}, {{borrower_name}}, {{attraction_name}}, {{corp_pass_number}}, {{visit_date}}";

export const PhysicalAttachmentVariables =
  "{{booking_date}}, {{borrower_name}}, {{attraction_name}}, {{membership_address}}, {{corp_pass_number}}, {{visit_date}}";
